### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kirschkern** [emmetio/atom-plugin#14]
Whenever I type a character after installing emmetio via apm I get an error.

Uncaught TypeError: Cannot read property 'length' of undefined
C:\Users\Daniel\.atom\packages\emmet-atom-plugin\node_modules\@emmetio\stream-reader\dist\stream-reader.cjs.js:10

Stack Trace
TypeError: Cannot read property 'length' of undefined
    at BufferStreamReader.StreamReader (C:\Users\Daniel\.atom\packages\emmet-atom-plugin\node_modules\@emmetio\stream-reader\dist\stream-reader.cjs.js:10:45)
    at BufferStreamReader (C:\Users\Daniel\.atom\packages\emmet-atom-plugin\lib\buffer-stream.js:19:3)
    at Object.getSuggestions (file:///C:/Users/Daniel/.atom/packages/emmet-atom-plugin/lib/autocomplete/math.js:24:19)
    at C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:298:19)

**Comment by girlandhercode** [comment]
I also get this same error after the last update.  The only way (I have found) to stop the error is to disable this plugin.
I am on Atom ``v1.16.0``

**Comment by sergeche** [comment]
Oops, sorry, should be fixed in recent commit
